version: 0.0
os: linux

#
# source: 인스턴스에 복사할 디렉터리 경로
# destination: 인스턴스에서 파일이 복사되는 위치
# overwrite: 복사할 위치에 파일이 있는 경우 대체

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

# object: 권한이 지정되는 파일 또는 디렉터리
# pattern (optional): 매칭되는 패턴에만 권한 부여
# owner (optional): object 의 소유자
# group (optional): object 의 그룹 이름


permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu


# location: hooks 에서 실행할 스크립트 위치
# timeout (optional): 스크립트 실행에 허용되는 최대 시간이며, 넘으면 배포 실패로 간주됨
# runas (optional): 스크립트를 실행하는 사용자

hooks:
  # 배포 이후 실행할 scripts를 찾는다.
#  files:
#    - source: /
#  destination: /home/ubuntu/
#  commands:
#    - mkdir -p /home/ubuntu/kiosk
  AfterInstall:
    - location: stop_was.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start_was.sh
      timeout: 60
      runas: ubuntu
