version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/web
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy-web.sh
      timeout: 60
      runas: ubuntu
