version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop_was.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start_was.sh
      timeout: 60
      runas: ubuntu
