spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiosk
    username: user
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            debug
