name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: kiosk-team5
  CODE_DEPLOY_APPLICATION_NAME: my-codedeploy-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: my-codedeploy-deployment-group

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Gradle
        run: |
          cd be/kiosk
          chmod +x gradlew
          ./gradlew clean build

      - name: Create temporary directory
        run: |
          mkdir -p deploy

      - name: Copy Jar, appspec.yml, start.sh and stop.sh
        run: |
          cp ./be/kiosk/build/libs/*.jar ./deploy/
          cp ./appspec.yml ./deploy/appspec.yml
          cp ./scripts/start.sh ./deploy/
          cp ./scripts/stop.sh ./deploy/

      - name: Make zip file
        run: zip -r ./kiosk-max-team-05-build.zip ./deploy/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload ZIP to S3
        run: |
          aws s3 cp ./kiosk-max-team-05-build.zip s3://${{ env.S3_BUCKET_NAME }}/deploy/kiosk-max-team-05-build.zip
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to CodeDeploy from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
            --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ env.S3_BUCKET_NAME }},key=deploy/kiosk-max-team-05-build.zip,bundleType=zip
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
